HTK_FEEDBACK_EMAIL_SUBJECT = 'New feedback from Hacktoolkit form'


FEEDBACK_REQUEST_TYPE_FEATURE = 'feature_request'
FEEDBACK_REQUEST_TYPE_BUG = 'bug_report'
FEEDBACK_REQUEST_TYPE_CONTENT = 'content_issue'
FEEDBACK_REQUEST_TYPE_SUPPORT = 'support_question'
FEEDBACK_REQUEST_TYPE_GENERAL = 'general_feedback'

FEEDBACK_REQUEST_TYPE_CHOICES = (
    (FEEDBACK_REQUEST_TYPE_FEATURE, 'Feature request'),
    (FEEDBACK_REQUEST_TYPE_BUG, 'Bug report'),
    (FEEDBACK_REQUEST_TYPE_CONTENT, 'Content issue'),
    (FEEDBACK_REQUEST_TYPE_SUPPORT, 'Support question'),
    (FEEDBACK_REQUEST_TYPE_GENERAL, 'General feedback'),
)

FEEDBACK_VISIBILITY_PUBLIC = 'public'
FEEDBACK_VISIBILITY_UNLISTED = 'unlisted'
FEEDBACK_VISIBILITY_PRIVATE = 'private'

FEEDBACK_VISIBILITY_CHOICES = (
    (FEEDBACK_VISIBILITY_PUBLIC, 'Public'),
    (FEEDBACK_VISIBILITY_UNLISTED, 'Unlisted'),
    (FEEDBACK_VISIBILITY_PRIVATE, 'Private'),
)

FEEDBACK_STATUS_NEW = 'new'
FEEDBACK_STATUS_UNDER_REVIEW = 'under_review'
FEEDBACK_STATUS_PLANNED = 'planned'
FEEDBACK_STATUS_IN_PROGRESS = 'in_progress'
FEEDBACK_STATUS_SHIPPED = 'shipped'
FEEDBACK_STATUS_DECLINED = 'declined'
FEEDBACK_STATUS_MERGED = 'merged'

FEEDBACK_STATUS_CHOICES = (
    (FEEDBACK_STATUS_NEW, 'New'),
    (FEEDBACK_STATUS_UNDER_REVIEW, 'Under review'),
    (FEEDBACK_STATUS_PLANNED, 'Planned'),
    (FEEDBACK_STATUS_IN_PROGRESS, 'In progress'),
    (FEEDBACK_STATUS_SHIPPED, 'Shipped'),
    (FEEDBACK_STATUS_DECLINED, 'Declined'),
    (FEEDBACK_STATUS_MERGED, 'Merged'),
)

FEEDBACK_EVENT_CREATED = 'created'
FEEDBACK_EVENT_VOTED = 'voted'
FEEDBACK_EVENT_UNVOTED = 'unvoted'
FEEDBACK_EVENT_COMMENTED = 'commented'
FEEDBACK_EVENT_STATUS_UPDATED = 'status_updated'
FEEDBACK_EVENT_FEEDBACK_CAPTURED = 'feedback_captured'
FEEDBACK_EVENT_ATTACHMENT_ADDED = 'attachment_added'
FEEDBACK_EVENT_MERGED = 'merged'
FEEDBACK_EVENT_HIDDEN = 'hidden'

FEEDBACK_EVENT_CHOICES = (
    (FEEDBACK_EVENT_CREATED, 'Created'),
    (FEEDBACK_EVENT_VOTED, 'Voted'),
    (FEEDBACK_EVENT_UNVOTED, 'Unvoted'),
    (FEEDBACK_EVENT_COMMENTED, 'Commented'),
    (FEEDBACK_EVENT_STATUS_UPDATED, 'Status updated'),
    (FEEDBACK_EVENT_FEEDBACK_CAPTURED, 'Feedback captured'),
    (FEEDBACK_EVENT_ATTACHMENT_ADDED, 'Attachment added'),
    (FEEDBACK_EVENT_MERGED, 'Merged'),
    (FEEDBACK_EVENT_HIDDEN, 'Hidden'),
)

FEEDBACK_DEFAULT_BOARD_SLUG = 'feedback'
