# Generated manually for django-htk feedback feature-request models.

# Django Imports
from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=24)),
                ('is_open', models.BooleanField(default=True)),
                ('allow_public_comments', models.BooleanField(default=True)),
                ('allow_public_voting', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_boards', to='sites.site')),
            ],
            options={
                'verbose_name': 'Feedback board',
                'verbose_name_plural': 'Feedback boards',
                'ordering': ('site', 'name'),
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('auto_assign_owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auto_assigned_feedback_categories', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='feedback.feedbackboard')),
            ],
            options={
                'verbose_name': 'Feedback category',
                'verbose_name_plural': 'Feedback categories',
                'ordering': ('board', 'sort_order', 'name'),
                'unique_together': {('board', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('feature_request', 'Feature request'), ('bug_report', 'Bug report'), ('content_issue', 'Content issue'), ('support_question', 'Support question'), ('general_feedback', 'General feedback')], default='feature_request', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('merged', 'Merged')], default='new', max_length=32)),
                ('internal_status', models.CharField(blank=True, max_length=64)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=24)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source_uri', models.CharField(blank=True, max_length=1024)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=1024)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('supporters_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('needs_followup', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='feedback.feedbackboard')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='feedback.feedbackcategory')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_requests', to='feedback.feedbackrequest')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owned_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='sites.site')),
            ],
            options={
                'verbose_name': 'Feedback request',
                'verbose_name_plural': 'Feedback requests',
                'ordering': ('-votes_count', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackrequest')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request comment',
                'verbose_name_plural': 'Feedback request comments',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback/attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('is_screenshot', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackrequestcomment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request attachment',
                'verbose_name_plural': 'Feedback request attachments',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('source_uri', models.CharField(blank=True, max_length=1024)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=1024)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='feedback.feedbackrequest')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_evidence', to='sites.site')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback evidence',
                'verbose_name_plural': 'Feedback evidence',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('merged', 'Merged')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('notify_supporters', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_status_updates', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='feedback.feedbackrequest')),
            ],
            options={
                'verbose_name': 'Feedback request status update',
                'verbose_name_plural': 'Feedback request status updates',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('voted', 'Voted'), ('unvoted', 'Unvoted'), ('commented', 'Commented'), ('status_updated', 'Status updated'), ('feedback_captured', 'Feedback captured'), ('attachment_added', 'Attachment added'), ('merged', 'Merged'), ('hidden', 'Hidden')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.feedbackrequest')),
            ],
            options={
                'verbose_name': 'Feedback request event',
                'verbose_name_plural': 'Feedback request events',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_status_updates', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='feedback.feedbackrequest')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request subscription',
                'verbose_name_plural': 'Feedback request subscriptions',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('importance', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedbackrequest')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request vote',
                'verbose_name_plural': 'Feedback request votes',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddIndex(model_name='feedbackrequest', index=models.Index(fields=['site', 'status'], name='feedback_fe_site_id_af55aa_idx')),
        migrations.AddIndex(model_name='feedbackrequest', index=models.Index(fields=['site', 'request_type'], name='feedback_fe_site_id_a85dd6_idx')),
        migrations.AddIndex(model_name='feedbackrequest', index=models.Index(fields=['site', 'visibility'], name='feedback_fe_site_id_ac2a88_idx')),
        migrations.AddIndex(model_name='feedbackrequest', index=models.Index(fields=['site', 'created_on'], name='feedback_fe_site_id_cc98cb_idx')),
        migrations.AddIndex(model_name='feedbackrequest', index=models.Index(fields=['board', 'category'], name='feedback_fe_board_i_35eeee_idx')),
        migrations.AddConstraint(model_name='feedbackrequestsubscription', constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('request', 'user'), name='feedback_unique_user_subscription')),
        migrations.AddConstraint(model_name='feedbackrequestsubscription', constraint=models.UniqueConstraint(condition=models.Q(user__isnull=True) & ~models.Q(email=''), fields=('request', 'email'), name='feedback_unique_email_subscription')),
        migrations.AddConstraint(model_name='feedbackrequestvote', constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('request', 'user'), name='feedback_unique_user_vote')),
        migrations.AddConstraint(model_name='feedbackrequestvote', constraint=models.UniqueConstraint(condition=models.Q(user__isnull=True) & ~models.Q(email=''), fields=('request', 'email'), name='feedback_unique_email_vote')),
    ]
