# Generated by Django 4.2.30 on 2026-10-04 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=128)),
                ("access_digest", models.CharField(max_length=64, unique=True)),
                ("refresh_digest", models.CharField(max_length=64, unique=True)),
                ("auth_hash", models.CharField(max_length=64)),
                ("access_expires_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=128)),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("challenge", models.CharField(max_length=43)),
                ("redirect_uri", models.CharField(max_length=200)),
                ("auth_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
